services:
  mongodb:
    image: 'mongo:latest'
    container_name: "mongodb"
    ports:
      - 27017:27017
  users-api:
    image: 'users-api:1.0'
    build: .
    container_name: "users-api"
    ports:
      - 8080:8080
    links:
      - mongodb
